# Generated by Django 5.1.1 on 2024-10-23 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('surname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('gmail', models.EmailField(max_length=100)),
                ('tlf', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=1000)),
                ('price', models.FloatField(max_length=6)),
                ('foto', models.CharField(max_length=100000)),
                ('alergens_List', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grill_And_Chill.alergen', to_field='description')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('order_Date', models.TimeField(auto_now=True)),
                ('ordered', models.FloatField()),
                ('products_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grill_And_Chill.product')),
                ('user_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grill_And_Chill.user')),
            ],
        ),
    ]
