# Generated by Django 5.1.1 on 2024-10-24 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grill_And_Chill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Alergen',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('alergens_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grill_And_Chill.alergen')),
                ('products_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grill_And_Chill.product')),
            ],
        ),
    ]
