# Generated by Django 5.1.1 on 2024-10-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grill_And_Chill', '0002_product_alergen'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
