# Generated by Django 5.1.1 on 2024-10-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grill_And_Chill', '0003_remove_order_products_id_product_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_Date',
            field=models.DateField(auto_now=True),
        ),
    ]
